### ISSUE TITLE
初次运行后得到了接近空的结果

### ISSUE THREAD

**Issue by Baigyth** [zillionare/boards#2]
* boards version: 0.14
* Python version: 3.10
* Operating System: Windows Server 2019 Datacenter

### Description
初次安装并运行程序后，没有fetch到全部的板块。望解答。

### What I Did
1. 按照readme指引，pip install zillionare-ths-boards
2. 发现不能自定义fetch时间，[主页](https://zillionare.github.io/boards/0.1.4.dev/)写的是“每天凌晨5点”。查看代码后git clone到本地，修改app.py默认运行小时为17，之后在本地目录下pip install .
3. win+r cmd boards serve
4. 自定义运行时间之后检查boards.zarr目录，发现文件体积异常小。命令行查询结果如下：
```
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS F:\Job\code\boards> boards status
------ board服务未运行 ------
行业板块数据还从未同步过。
概念板块数据还从未同步过。
PS F:\Job\code\boards> boards new_boards
        date  name    code  members
0 2023-04-20   太赫兹  300795       16
1 2023-04-19  猴痘概念  308941       58
2 2023-04-19  粮食概念  308956       35
PS F:\Job\code\boards> boards new_members
'concept/members'
PS F:\Job\code\boards> boards latest_boards
        date  name    code  members
0 2023-04-20   太赫兹  300795       16
1 2023-04-19  猴痘概念  308941       58
2 2023-04-19  粮食概念  308956       35
```
5. 检查c:\var\log\boards\server.log，好像有两处网络问题导致的报错，最后一行显示"executed successfully"……
[server.log](https://github.com/zillionare/boards/files/11333291/server.log)

**Comment by zillionare** [comment]
我们开发的软件一般默认是在ubuntu下运行。只进行了ubuntu下的测试。不过问题已收到。正在查看。
